# -*- coding: utf-8 -*-
"""PRUEBA_Proyecto_Final_TalentoTech_Grupo_AH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o5IyGvpxgEmbH5ltBxay88vK9xyCr4X8

# 📊 Análisis Exploratorio y Modelamiento Predictivo de la Asistencia de Estudiantes para la Predicción de la Deserción Académica

## 🎯 Objetivo
Construir un dataset sintético que permita analizar el comportamiento de estudiantes y predecir la deserción académica utilizando técnicas de análisis exploratorio y modelos predictivos.

---

## 🧩 Estructura del modelo de datos

Se generan las siguientes tablas:

- ESTUDIANTES (dimensión)
- ASISTENCIA (hechos)
- ACADEMICO (desempeño)
- COMPORTAMIENTO (uso de plataforma)
- DATA_FINAL (dataset analítico)

---

## 🧠 Enfoque analítico

El proyecto busca:
- Identificar patrones de asistencia
- Analizar variables que influyen en la deserción
- Construir un modelo predictivo

## 🟣 Librerías
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc

np.random.seed(42)

"""## 📌 Tabla ESTUDIANTES

Contiene información demográfica y socioeconómica.
"""

# ===========================
#     TABLA ESTUDIANTES
# ===========================
n = 300

estudiantes = pd.DataFrame({
    "id_estudiante": range(1000, 1000+n),

    # Demográficas
    "edad": np.random.randint(16, 35, n),
    "genero": np.random.choice(["M", "F"], n),
    "ciudad": np.random.choice(['Bogotá', 'Medellín', 'Cali', 'Barranquilla'], n),

    # Socioeconómicas
    "estrato": np.random.randint(1, 7, n),
    "trabaja": np.random.choice([0,1], n, p=[0.6,0.4]),
    "tiene_internet": np.random.choice([0,1], n, p=[0.3,0.7]),

    # Variables enriquecidas 🔥
    "educacion_padres": np.random.choice(
        ["Primaria", "Secundaria", "Universitaria"], n
    ),
    "apoyo_familiar": np.random.randint(1,6,n)  # escala 1-5
})

# Variable derivada (nivel senior 😏)
estudiantes["riesgo_economico"] = np.where(estudiantes["estrato"] <= 2, 1, 0)

estudiantes.head()

"""## 📌 Tabla ASISTENCIA

Registra el comportamiento diario de asistencia.
"""

# ===========================
#     TABLA ASISTENCIA
# ===========================
fechas = pd.date_range(start="2023-01-01", periods=90)

asistencia_list = []

for est in estudiantes["id_estudiante"]:

    # Probabilidad base según contexto (🔥 realista)
    estrato = estudiantes.loc[estudiantes["id_estudiante"] == est, "estrato"].values[0]
    trabaja = estudiantes.loc[estudiantes["id_estudiante"] == est, "trabaja"].values[0]

    base_prob = np.random.uniform(0.75, 0.95)

    # Ajustes por contexto
    if estrato <= 2:
        base_prob -= 0.1
    if trabaja == 1:
        base_prob -= 0.05

    tendencia = np.random.uniform(0.0005, 0.002)  # deterioro progresivo

    for i, f in enumerate(fechas):

        # deterioro en el tiempo
        prob = base_prob - (i * tendencia)

        # ruido
        prob += np.random.normal(0, 0.02)

        # límites
        prob = max(0.3, min(prob, 0.98))

        asistencia_list.append({
            "id_estudiante": est,
            "fecha": f,
            "asistio": np.random.choice([1,0], p=[prob, 1-prob])
        })

asistencia = pd.DataFrame(asistencia_list)

asistencia.head()

asistencia["asistio"].mean()

asistencia.groupby("id_estudiante")["asistio"].mean().describe()

asistencia.groupby("id_estudiante")["asistio"].mean().hist(bins=20)
plt.title("Distribución de tasa de asistencia por estudiante")
plt.show()

asistencia["falta"] = 1 - asistencia["asistio"]

asistencia["racha_fallas"] = asistencia.groupby("id_estudiante")["falta"].cumsum()

asistencia.isna().sum()

"""## 📌 Tabla ACADEMICO

Contiene variables relacionadas con el desempeño académico.
"""

# ===========================
#     TABLA ACADEMICO
# ===========================

# Calculamos tasa de asistencia (ya la tienes)
asistencia_prom = asistencia.groupby("id_estudiante")["asistio"].mean().reset_index()

academico = asistencia_prom.copy()

# Promedio depende de asistencia (🔥 clave)
academico["promedio"] = np.round(
    2.0 + academico["asistio"] * 3 + np.random.normal(0, 0.3, len(academico)),
    2
).clip(2.0, 5.0)

# Materias reprobadas inverso a asistencia
academico["materias_reprobadas"] = np.round(
    (1 - academico["asistio"]) * 6 + np.random.normal(0,1,len(academico))
).clip(0,6)

# Inasistencias previas (relacionadas también)
academico["inasistencias_previas"] = np.round(
    (1 - academico["asistio"]) * 20 + np.random.normal(0,3,len(academico))
).clip(0,20)

# Renombrar
academico.rename(columns={"asistio":"tasa_asistencia"}, inplace=True)

#Garantizar que  la vble materias reprobadas sea entera
academico["materias_reprobadas"] = academico["materias_reprobadas"].astype(int)

academico.head()

"""## 📌 Tabla COMPORTAMIENTO

Variables relacionadas con el uso de plataformas educativas.
"""

# ===============================
#     TABLA COMPORTAMIENTO
# ===============================

# usamos tasa de asistencia
asistencia_prom = asistencia.groupby("id_estudiante")["asistio"].mean().reset_index()

comportamiento = asistencia_prom.copy()

# logins dependen de asistencia
comportamiento["logins"] = np.round(
    comportamiento["asistio"] * 120 + np.random.normal(0,15,len(comportamiento))
).clip(5,150)

# tiempo en plataforma (horas)
comportamiento["tiempo_plataforma"] = np.round(
    comportamiento["asistio"] * 12 + np.random.normal(0,2,len(comportamiento))
).clip(1,15)

# interacciones
comportamiento["interacciones"] = np.round(
    comportamiento["asistio"] * 50 + np.random.normal(0,8,len(comportamiento))
).clip(0,50)

# renombrar
comportamiento.rename(columns={"asistio":"tasa_asistencia"}, inplace=True)

# convertir a enteros
comportamiento["logins"] = comportamiento["logins"].astype(int)
comportamiento["tiempo_plataforma"] = comportamiento["tiempo_plataforma"].astype(int)
comportamiento["interacciones"] = comportamiento["interacciones"].astype(int)

comportamiento.head()

"""## 📌 Integración de datos

Se consolidan todas las fuentes en un dataset analítico.
"""

# =============================
#     INTEGRACIÓN DATA
# =============================

data = estudiantes.merge(academico, on="id_estudiante") \
                  .merge(comportamiento, on="id_estudiante")

# ARREGLA DUPLICADOS
data["tasa_asistencia"] = data["tasa_asistencia_x"]

# Elimina columnas duplicadas
data.drop(["tasa_asistencia_x", "tasa_asistencia_y"], axis=1, inplace=True)

data.columns

# ==============================
#     LÓGICA DE DESERCIÓN
# ==============================

data["riesgo"] = 0

data["riesgo"] += (1 - data["tasa_asistencia"]) * 3
data["riesgo"] += (3 - data["promedio"]).clip(0,3)
data["riesgo"] += (data["materias_reprobadas"] / 2)
data["riesgo"] += (1 - (data["logins"] / 100)) * 2
data["riesgo"] += (data["inasistencias_previas"] / 10)

data["riesgo"] += np.random.normal(0, 0.5, len(data))

data["desercion"] = np.where(data["riesgo"] > 3.5, 1, 0)

data["desercion"].value_counts(normalize=True)

data.head()

data = data.drop(columns=["riesgo"])

"""##Exportar en CSV y SQL

"""

#Exporta data en CVS
data.to_csv("DATA_FINAL.csv", index=False)

#Exporte en SQL
import sqlite3

# crear conexión
conn = sqlite3.connect("data_estudiantes.db")

# guardar tabla
data.to_sql("estudiantes", conn, if_exists="replace", index=False)

conn.close()

### REVISAR DE AQUI EN ADELANTE
sns.countplot(x="desercion", data=data)
plt.title("Distribución de Deserción")
plt.show()

"""# 📊 Análisis Exploratorio de Datos

📌 Distribución deserción
"""

sns.countplot(x="desercion", data=data)
plt.title("Distribución de Deserción")
plt.show()

"""📌 Asistencia vs Deserción"""

sns.boxplot(x="desercion", y="tasa_asistencia", data=data)
plt.title("Asistencia vs Deserción")
plt.show()

"""📌 Promedio vs Deserción"""

sns.boxplot(x="desercion", y="promedio", data=data)
plt.show()

"""📌 Correlación"""

plt.figure(figsize=(10,6))
sns.heatmap(data.corr(), annot=True, cmap="coolwarm")
plt.title("Mapa de correlación")
plt.show()

"""# 🤖 Modelo Predictivo (Regresión Logística)

Se busca predecir la probabilidad de deserción.
"""

X = data.drop(["desercion","id_estudiante"], axis=1)
y = data["desercion"]

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

"""📌 Matriz de confusión"""

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d")
plt.title("Matriz de Confusión")
plt.show()

"""📌 ROC Curve"""

y_prob = model.predict_proba(X_test)[:,1]

fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f"AUC={roc_auc:.2f}")
plt.plot([0,1],[0,1])
plt.legend()
plt.title("ROC Curve")
plt.show()

"""📌 Importancia de variables"""

coef = pd.Series(model.coef_[0], index=X.columns)
coef.sort_values().plot(kind="barh", figsize=(8,6))
plt.title("Importancia de variables")
plt.show()

"""## 📌 Conclusiones

- La asistencia es el principal predictor de deserción
- Variables como logins y promedio académico influyen significativamente
- Se pueden identificar estudiantes en riesgo de forma temprana

## 🚀 Valor del proyecto

Este modelo permite anticipar la deserción y apoyar estrategias de retención académica basadas en datos.
"""